services:
  db:
    image: postgres:14.20-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dumarket_${RAILS_ENV:-development}}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine

  web:
    build:
      context: .
      args:
        - RUBY_VERSION=${RUBY_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - YARN_VERSION=${YARN_VERSION}
    command: ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/rails
      - /rails/public/assets
    ports:
      - "3000:3000"
      # - "127.0.0.1:9394:9394" # prometheus metrics coming from rails/yabeda
    secrets:
      - db_password
    environment:
      - RAILS_LOG_PATH=${RAILS_LOG_PATH}
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./database_password.txt
