x-fluentd-logging: &fluentd-logging
  driver: "fluentd"
  options:
    fluentd-address: "127.0.0.1:8006"
    fluentd-async: "true"

services:
  caddy:
    image: caddy:2.11.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    logging: *fluentd-logging

  db:
    environment:
      POSTGRES_DB: dumarket_${RAILS_ENV:-production}

  redis:

  web:
    build:
      context: .
      args:
        - RUBY_VERSION=${RUBY_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - YARN_VERSION=${YARN_VERSION}
    command: ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes: !override
      - /rails/public/assets
    ports: !reset
    secrets:
      - db_password
      - source: rails_master_key
        target: /rails/config/master.key
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password

  otel-collector:

volumes:
  caddy_data:
  caddy_config:

# please create the proper /var/secrets/ dir first
secrets:
  db_password:
    file: /var/secrets/database_password.txt
  rails_master_key:
    file: /var/secrets/master.key

configs:
  caddyfile:
    file: ./Caddyfile
